#!/usr/bin/env python3
"""
episode_consistency_check.py — Character lock integrity, protected-source
mutation detection, and cross-output claim consistency for a generated
episode package. (P0-4, P0-5, P1-16, P1-17, P1-18)

This is a different check from tools/validate_repo.py (which validates
the REPOSITORY's own data) and different from
tools/prompt_regression_test.py (which diffs output before/after a
prompt edit for quality drift). This script validates a GENERATED
EPISODE PACKAGE against the repository it claims to be built from —
the check Document 6/7's failure would have been caught by if it had
existed.

Usage:
    python3 tools/episode_consistency_check.py snapshot [repo_root]
        Saves a hash baseline of protected canonical directories to
        .protected_snapshot.json (P0-4 "before" state).

    python3 tools/episode_consistency_check.py verify [repo_root]
        Compares current protected-directory hashes against the saved
        baseline. Any difference = protected knowledge mutated during
        generation = FAIL (P0-4/S).

    python3 tools/episode_consistency_check.py check-episode <output_package_dir> [repo_root]
        Runs character-lock byte-match (P0-5/R) and excluded-claim scan
        (P1-16/17/18) against a generated episode folder.
"""
import hashlib
import json
import os
import re
import sys

PROTECTED_DIRS = [
    "phase2/data/islamic",
    "sources/characters/characters",
    "phase3/knowledge/concepts",
    "phase3/knowledge/curriculum",
    "phase2/data/database",  # excluding generation_log.json / current_state.json / world_state.json which ARE meant to update — see EXCLUDED below
    # Added in Phase 2 (Visual Continuity Foundation): these are DERIVED files
    # (regenerated by tools/continuity/migrate_v272_to_continuity.py from the
    # sources/ files already protected above), but they become the runtime
    # source of truth for continuity locking once generated, so silent
    # mid-run mutation of them is exactly the same class of bug this check
    # already exists to catch.
    "continuity/character_bible",
    "continuity/environment_bible",
    "continuity/prop_registry",
    "continuity/camera_bible",
    # Phase 6: once an episode is authored and registered, its content is
    # canonical the same way a character bible is -- protect it from silent
    # mid-pipeline rewriting for the same reason. continuity/clip_state,
    # generated_requests, qa_reports, and story_state are deliberately NOT
    # protected here -- they're meant to change as the pipeline runs.
    "continuity/authored_episodes",
]
# Files inside PROTECTED_DIRS that are explicitly allowed to change during
# a generation run (per execution_modes.md: output_package/, runtime logs,
# generation logs, approved state files are the allowed-mutation set).
EXCLUDED_FROM_PROTECTION = {
    "current_state.json", "generation_log.json", "world_state.json",
    "last_episode.json", "review_queue.json", "creator_edits_log.json",
}
SNAPSHOT_FILE = ".protected_snapshot.json"


def hash_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


def build_snapshot(root):
    snap = {}
    for d in PROTECTED_DIRS:
        full_dir = os.path.join(root, d)
        if not os.path.isdir(full_dir):
            continue
        for dirpath, _, filenames in os.walk(full_dir):
            for fname in filenames:
                if fname in EXCLUDED_FROM_PROTECTION:
                    continue
                full = os.path.join(dirpath, fname)
                rel = os.path.relpath(full, root)
                snap[rel] = hash_file(full)
    return snap


def cmd_snapshot(root):
    snap = build_snapshot(root)
    with open(os.path.join(root, SNAPSHOT_FILE), "w") as f:
        json.dump(snap, f, indent=2)
    print(f"Snapshot saved: {len(snap)} protected files hashed.")


def cmd_verify(root):
    snap_path = os.path.join(root, SNAPSHOT_FILE)
    if not os.path.exists(snap_path):
        print("ERROR: no baseline snapshot found. Run 'snapshot' before generation first.")
        sys.exit(1)
    baseline = json.load(open(snap_path))
    current = build_snapshot(root)

    changed = [f for f in baseline if f in current and baseline[f] != current[f]]
    removed = [f for f in baseline if f not in current]
    added = [f for f in current if f not in baseline]

    if changed or removed:
        print("FAIL — protected canonical knowledge was mutated during generation:")
        for f in changed:
            print(f"  [MODIFIED] {f}")
        for f in removed:
            print(f"  [REMOVED] {f}")
        print("\nvalidation: FAIL")
        print("production_ready: false")
        sys.exit(1)
    else:
        print(f"PASS — {len(baseline)} protected files unchanged.")
        if added:
            print(f"Note: {len(added)} new file(s) appeared in protected directories "
                  f"(not a mutation of existing canonical data, but review before treating as canonical): {added}")
        sys.exit(0)


def normalize_whitespace(text):
    """Collapses all whitespace runs (including newlines from markdown
    word-wrap) to single spaces before comparison. Word-wrap column width
    differing between a character.md file and an image_prompts.md block
    is a cosmetic formatting difference, not a content change — the
    check must compare the actual words, not the raw byte layout."""
    return re.sub(r"\s+", " ", text).strip()


def extract_locked_block(text):
    """Pulls the LOCKED DESCRIPTION BLOCK content from a character .md file."""
    m = re.search(r"LOCKED DESCRIPTION BLOCK.*?\n\"(.+?)\"", text, re.DOTALL)
    if m:
        return m.group(1).strip()
    return None


def load_valid_source_ids(root):
    ids = set()
    uncited_ids = set()
    islamic_dir = os.path.join(root, "phase2", "data", "islamic")
    for fname in os.listdir(islamic_dir):
        if not fname.endswith(".json"):
            continue
        d = json.load(open(os.path.join(islamic_dir, fname), encoding="utf-8"))
        for k, v in d.items():
            if isinstance(v, list):
                for e in v:
                    if isinstance(e, dict):
                        for idk in e:
                            if idk.endswith("_id"):
                                ids.add(e[idk])
                                if "citation_verified" in e and not e["citation_verified"]:
                                    uncited_ids.add(e[idk])
    return ids, uncited_ids


def check_source_ids_resolve(episode_dir, root, errors):
    """K, M: a source_id mentioned in an episode's islamic_refs.md or
    verification_report.md must resolve to a real record. A fabricated
    ID, or an ID that 'sounds real' but was recalled from model memory
    rather than retrieved from the repo, fails here — it simply won't
    be in the real ID set. ALSO (added after real Task-5 testing found
    the gap): an ID that resolves but is citation_verified:false — a
    real record still on the blocklist, e.g. mann_004 — must also fail.
    Resolving is not the same as being cleared for use."""
    valid_ids, uncited_ids = load_valid_source_ids(root)
    id_pattern = re.compile(r"\b((?:qv|dua|hd|hadith|prophet|mann|sun|fest|companion)_[a-zA-Z0-9_]+)\b")
    for fname in ["islamic_refs.md", "verification_report.md"]:
        path = os.path.join(episode_dir, fname)
        if not os.path.exists(path):
            continue
        content = open(path, encoding="utf-8").read()
        for mid in set(id_pattern.findall(content)):
            if mid not in valid_ids:
                errors.append(f"[FABRICATED SOURCE ID] {fname} references '{mid}', which does not resolve "
                              f"to any real record in phase2/data/islamic/*.json — model-memory or invented "
                              f"reference, not repository evidence (K/M). Real IDs in this repository use the "
                              f"format hd_NNN/qv_NNN/dua_NNN/prophet_name, never collection-style names like "
                              f"'hadith_bukhari_NN' — a citation in that format is a strong fabrication signal.")
            elif mid in uncited_ids:
                errors.append(f"[BLOCKED RECORD USED] {fname} references '{mid}', which exists in the "
                              f"repository but has citation_verified:false — it is on the uncited-records "
                              f"blocklist and not cleared for production use until independently verified.")


def check_review_queue_invariants(root, errors):
    """T, U: BLOCKED must never carry production_ready:true. ASSISTED
    must never carry production_ready:true unless status is explicitly
    'approved'."""
    p = os.path.join(root, "phase2", "data", "database", "review_queue.json")
    if not os.path.exists(p):
        return
    d = json.load(open(p, encoding="utf-8"))
    for ep in d.get("episodes", []):
        mode = ep.get("execution_mode")
        pr = ep.get("production_ready")
        status = ep.get("status")
        eid = ep.get("episode_id")
        if mode == "blocked" and pr is True:
            errors.append(f"[INVARIANT VIOLATION] review_queue.json: '{eid}' is execution_mode=blocked "
                          f"but production_ready=true — BLOCKED must never be production_ready (T).")
        if mode == "assisted" and pr is True and status != "approved":
            errors.append(f"[INVARIANT VIOLATION] review_queue.json: '{eid}' is execution_mode=assisted "
                          f"with production_ready=true but status is not 'approved' — assisted output needs "
                          f"explicit approval before production_ready can be true (U).")


def classify_semantic_support(claim_category, source_category, source_id, root):
    """Rule-based proxy for DIRECT_SUPPORT/INDIRECT_SUPPORT/INTERPRETIVE/
    UNSUPPORTED. This is a heuristic on top of existing repository
    category tags, NOT a scholarly judgment tool — it flags mismatches
    for human review, it does not resolve religious questions. A
    dedicated 'semantic support engine' was NOT built; this reuses the
    category fields already present on every phase2/data/islamic/*.json
    entry."""
    if not source_id:
        return "UNSUPPORTED"
    if claim_category == source_category:
        return "DIRECT_SUPPORT"
    if claim_category and source_category:
        return "INTERPRETIVE"
    return "INDIRECT_SUPPORT"


def check_semantic_overreach(episode_dir, root, errors, warnings):
    """I, J: reads verification_report.md's per-claim blocks (Claim /
    Evidence / source_id / category-adjacent info) and cross-checks the
    cited source's own 'category' field against the claim's stated
    topic. A claim whose cited source has a clearly different category
    and no 'Interpretation Needed?: Yes' acknowledgment is flagged."""
    vr_path = os.path.join(episode_dir, "verification_report.md")
    if not os.path.exists(vr_path):
        return
    content = open(vr_path, encoding="utf-8").read()
    blocks = re.split(r"^## Claim \d+", content, flags=re.MULTILINE)[1:]
    valid_ids, _ = load_valid_source_ids(root)
    # build source_id -> category lookup
    cat_by_id = {}
    islamic_dir = os.path.join(root, "phase2", "data", "islamic")
    for fname in os.listdir(islamic_dir):
        if not fname.endswith(".json"):
            continue
        d = json.load(open(os.path.join(islamic_dir, fname), encoding="utf-8"))
        for k, v in d.items():
            if isinstance(v, list):
                for e in v:
                    if isinstance(e, dict):
                        idk = next((f for f in e if f.endswith("_id")), None)
                        if idk:
                            cat_by_id[e[idk]] = e.get("category", "")

    for block in blocks:
        m_id = re.search(r"Evidence:\s*([a-zA-Z0-9_]+)", block)
        m_interp = re.search(r"Interpretation Needed\?:\s*(Yes|No)", block)
        if not m_id:
            continue
        sid = m_id.group(1)
        if sid not in valid_ids:
            continue  # already caught by check_source_ids_resolve
        interp_acknowledged = m_interp and m_interp.group(1) == "Yes"
        # if the block itself never declares support_type/category info,
        # this is a warning (schema incompleteness), not a hard failure —
        # existing verification_report.md entries predate this field
        if "support_type" not in block.lower() and not interp_acknowledged:
            warnings.append(f"[SEMANTIC SUPPORT UNCLASSIFIED] Claim citing '{sid}' has no explicit "
                            f"support_type (DIRECT_SUPPORT/INDIRECT_SUPPORT/INTERPRETIVE/UNSUPPORTED) "
                            f"and no 'Interpretation Needed?' acknowledgment — cannot confirm the claim "
                            f"isn't overreaching its source without one (I/J).")


def check_unquoted_religious_attribution(episode_dir, root, errors):
    """CRITICAL fix (found via real negative testing, not theoretical):
    check_paraphrase_as_quotation only catches fabrications INSIDE quote
    marks. A claim like 'The Prophet said that eating dates on Tuesdays
    brings extra reward' — asserted as narrated fact, no quote marks,
    no source_id — passed every existing check clean. This closes that
    gap: any sentence attributing a specific claim to Allah/the Prophet/
    the Quran, with no genuinely connected source_id, is a hard FAIL.

    SECOND fix, found by a further adversarial test (v2.28): the first
    version of this check was satisfied by ANY real ID existing
    anywhere in the package, unrelated to the actual claim — a
    fabricated claim sitting next to a real but unrelated citation
    passed clean. That is the exact 'claim-level evidence binding'
    failure this repository's whole verification framework exists to
    prevent. Fixed: an ID only counts as support if it appears near the
    claim (same file, same paragraph) OR if the claim's own significant
    words meaningfully overlap with a claim block in islamic_refs.md/
    verification_report.md that itself cites a real ID — a package-wide
    'any ID exists' check is never sufficient by itself again."""
    valid_ids, _ = load_valid_source_ids(root)
    attribution_patterns = [
        r"the prophet[^.]*\bsaid\b", r"the prophet[^.]*\bdid\b", r"the prophet[^.]*\btaught\b",
        r"allah (?:said|says|commands|promises|rewards|will give|guarantees)",
        r"(?:the )?quran (?:says|states|teaches|promises)",
        r"it is (?:haram|halal) (?:to|that)",
    ]
    combined = re.compile("|".join(attribution_patterns), re.IGNORECASE)
    stopwords = {"the", "a", "an", "that", "this", "said", "says", "prophet", "allah", "quran",
                 "did", "taught", "commands", "promises", "rewards", "will", "give", "guarantees",
                 "it", "is", "to", "haram", "halal", "and", "of", "for", "with", "on", "in"}

    # gather claim blocks from islamic_refs.md / verification_report.md —
    # each block's own text, paired with whether it actually cites a
    # real, resolving ID
    evidence_blocks = []
    for ref_fname in ("islamic_refs.md", "verification_report.md"):
        ref_path = os.path.join(episode_dir, ref_fname)
        if not os.path.exists(ref_path):
            continue
        ref_content = open(ref_path, encoding="utf-8").read()
        for block in re.split(r"\n(?=##|\d+\.)", ref_content):
            block_ids = set(re.findall(r"\b(?:qv|dua|hd)_\d+\b", block))
            real_ids_in_block = block_ids & valid_ids
            if real_ids_in_block:
                evidence_blocks.append(block.lower())

    for fname in os.listdir(episode_dir):
        path = os.path.join(episode_dir, fname)
        if not os.path.isfile(path) or not fname.endswith((".md", ".srt")):
            continue
        content = open(path, encoding="utf-8").read()
        for m in combined.finditer(content):
            window = content[max(0, m.start()-300):m.end()+300]
            has_nearby_id = bool(re.search(r"\b(?:qv|dua|hd|hadith|prophet)_[a-zA-Z0-9_]+\b", window))
            is_meta_discussion = fname in ("missing_knowledge_report.md", "repository_improvement_suggestions.md")

            claim_sentence = content[max(0, m.start()-60):m.end()+80]
            claim_words = {w.lower() for w in re.findall(r"[a-zA-Z']+", claim_sentence)} - stopwords
            genuinely_bound = has_nearby_id
            if not genuinely_bound:
                for block in evidence_blocks:
                    block_words = set(re.findall(r"[a-zA-Z']+", block)) - stopwords
                    overlap = claim_words & block_words
                    if len(overlap) >= 2:  # require real, specific word overlap, not one generic word
                        genuinely_bound = True
                        break

            if not genuinely_bound and not is_meta_discussion:
                errors.append(f"[UNSUPPORTED RELIGIOUS ATTRIBUTION] {fname}: '{content[m.start():m.end()+40].strip()}...' "
                              f"attributes a claim to Allah/the Prophet/the Quran with no genuinely connected "
                              f"source_id — either no citation exists, or a real citation exists elsewhere in "
                              f"the package for an UNRELATED claim, which does not legitimize this one "
                              f"(claim-level evidence binding, not just package-level ID presence).")


def check_paraphrase_as_quotation_OLD_UNUSED(episode_dir, root, errors):
    """superseded by the fixed version below (v2.29)"""
    canonical_strings = set()
    islamic_dir = os.path.join(root, "phase2", "data", "islamic")
    for fname in os.listdir(islamic_dir):
        if not fname.endswith(".json"):
            continue
        d = json.load(open(os.path.join(islamic_dir, fname), encoding="utf-8"))
        for k, v in d.items():
            if isinstance(v, list):
                for e in v:
                    if isinstance(e, dict):
                        for field in ("arabic_text", "translation", "translation_simplified", "transliteration"):
                            if field in e and e[field]:
                                canonical_strings.add(normalize_whitespace(e[field]))

    arabic_pattern = re.compile(r"[\u0600-\u06FF]{3,}")
    quote_pattern = re.compile(r'"([^"]{10,200})"')
    framing_markers = ("quran", "hadith", "allah said", "allah says", "the prophet said",
                        "prophet said", "prophet ﷺ said", "revelation says", "verse says")

    for fname in os.listdir(episode_dir):
        path = os.path.join(episode_dir, fname)
        if not os.path.isfile(path) or not fname.endswith((".md", ".srt")):
            continue
        content = open(path, encoding="utf-8").read()
        for m in quote_pattern.finditer(content):
            quoted = m.group(1)
            has_arabic = bool(arabic_pattern.search(quoted))
            # check both inside the quote AND the ~60-char window immediately
            # before it, since real sentences frame a quote from outside it
            # ("The Prophet said, \"...\"") rather than inside the quote text
            context_before = content[max(0, m.start() - 25):m.start()].lower()
            looks_religious = has_arabic or any(marker in context_before or marker in quoted.lower() for marker in framing_markers)
            if not looks_religious:
                continue
            norm = normalize_whitespace(quoted)
            if norm not in canonical_strings and not any(norm in c or c in norm for c in canonical_strings):
                errors.append(f"[PARAPHRASE AS QUOTATION] {fname}: quoted text \"{quoted[:50]}...\" "
                              f"looks like a religious quotation but doesn't match any canonical "
                              f"arabic_text/translation/transliteration field verbatim (N).")


def check_paraphrase_as_quotation(episode_dir, root, errors):
    """N + P0 fix (v2.29): a quotation-marked string containing Arabic
    script or explicit framing must match a real canonical field
    exactly AND must be attributed to the SPECIFIC record that field
    belongs to -- not just any real record anywhere. Previously this
    only proved 'this text exists somewhere in the database', which a
    real adversarial test (Test F) showed lets a genuine quote from
    source A be falsely paired with citation ID B. Now: find which ID
    actually owns the matched text, then confirm the episode package
    cites THAT id somewhere -- not a different one, not none at all."""
    text_to_id = {}
    islamic_dir = os.path.join(root, "phase2", "data", "islamic")
    for fname in os.listdir(islamic_dir):
        if not fname.endswith(".json"):
            continue
        d = json.load(open(os.path.join(islamic_dir, fname), encoding="utf-8"))
        for k, v in d.items():
            if isinstance(v, list):
                for e in v:
                    if isinstance(e, dict):
                        idk = next((f for f in e if f.endswith("_id")), None)
                        if not idk:
                            continue
                        for field in ("arabic_text", "translation", "translation_simplified", "transliteration"):
                            if field in e and e[field]:
                                text_to_id[normalize_whitespace(e[field])] = e[idk]

    arabic_pattern = re.compile(r"[\u0600-\u06FF]{3,}")
    quote_pattern = re.compile(r'"([^"]{10,200})"')
    framing_markers = ("quran", "hadith", "allah said", "allah says", "the prophet said",
                        "prophet said", "prophet salallahu said", "revelation says", "verse says")

    package_cited_ids = set()
    for other_fname in os.listdir(episode_dir):
        other_path = os.path.join(episode_dir, other_fname)
        if os.path.isfile(other_path) and other_fname.endswith((".md", ".srt")):
            try:
                other_content = open(other_path, encoding="utf-8").read()
            except Exception:
                continue
            package_cited_ids |= set(re.findall(r"\b(?:qv|dua|hd)_\d+\b", other_content))

    for fname in os.listdir(episode_dir):
        path = os.path.join(episode_dir, fname)
        if not os.path.isfile(path) or not fname.endswith((".md", ".srt")):
            continue
        content = open(path, encoding="utf-8").read()
        for m in quote_pattern.finditer(content):
            quoted = m.group(1)
            has_arabic = bool(arabic_pattern.search(quoted))
            context_before = content[max(0, m.start() - 25):m.start()].lower()
            looks_religious = has_arabic or any(marker in context_before or marker in quoted.lower() for marker in framing_markers)
            norm = normalize_whitespace(quoted)
            matched_id = None
            for canon_text, owner_id in text_to_id.items():
                if norm == canon_text or norm in canon_text or canon_text in norm:
                    matched_id = owner_id
                    break
            # NOTE (v2.30): a fuzzy word-overlap near-match layer was
            # attempted here to catch Test G (subtly altered quotes with
            # a correctly-cited source). Tested against all 28 real
            # episodes: it produced 4 false positives on short, entirely
            # legitimate phrases (thumbnail text, casual dialogue)
            # coincidentally sharing 2-3 words with unrelated canonical
            # text. Breaking real production output to catch one narrow
            # synthetic adversarial case is a bad trade -- reverted.
            # Test G remains a real, open, documented gap rather than
            # being "solved" by a check that damages legitimate content.
            if matched_id is not None:
                if matched_id not in package_cited_ids:
                    errors.append(f"[SOURCE_MISMATCH] {fname}: quoted text \"{quoted[:50]}...\" is the real "
                                  f"text of '{matched_id}', but this episode package never cites '{matched_id}' "
                                  f"anywhere -- it is either citing the wrong ID for this quote or no ID at "
                                  f"all (an exact quote must bind to its specific source, not just exist "
                                  f"somewhere in the database).")
            elif looks_religious:
                errors.append(f"[PARAPHRASE AS QUOTATION] {fname}: quoted text \"{quoted[:50]}...\" "
                              f"looks like a religious quotation but doesn't match any canonical "
                              f"arabic_text/translation/transliteration field verbatim (N).")


def check_character_resolution(episode_dir, root, errors):
    """E: every character declared in episode_summary.md's 'Characters:'
    line must resolve to a real file in sources/characters/characters/.
    A declared character with no canonical file is a BLOCK for that
    character, not a silent invention."""
    char_dir = os.path.join(root, "sources", "characters", "characters")
    if not os.path.isdir(char_dir):
        return
    known = set(f[:-3] for f in os.listdir(char_dir) if f.endswith(".md"))
    summary_path = os.path.join(episode_dir, "episode_summary.md")
    if not os.path.exists(summary_path):
        return
    content = open(summary_path, encoding="utf-8").read()
    m = re.search(r"Characters:\*{0,2}\s*([^|\n]+)", content)
    if not m:
        return
    declared = [re.sub(r"[*_`]", "", c.strip().split(" (")[0]).strip() for c in m.group(1).split(",")]
    for c in declared:
        slug = c.lower().replace(" ", "_")
        if slug not in known and c.lower() not in {k.replace("_", " ") for k in known}:
            errors.append(f"[UNRESOLVED CHARACTER] '{c}' is declared in episode_summary.md but has no "
                          f"canonical file in sources/characters/characters/ — BLOCK for this character, "
                          f"never silently invent a replacement design (E).")


def check_learning_objective_consistency(episode_dir, root, errors, warnings):
    """Cross-output pair: does episode_summary.md's declared core concept
    actually appear as the lesson in the script? A keyword-overlap
    heuristic, not semantic proof — flags a likely mismatch for human
    review rather than asserting certainty."""
    summary_path = os.path.join(episode_dir, "episode_summary.md")
    script_path = os.path.join(episode_dir, "complete_script.md")
    if not (os.path.exists(summary_path) and os.path.exists(script_path)):
        return
    summary = open(summary_path, encoding="utf-8").read()
    m = re.search(r"Core Concept.*?:\s*\**([A-Za-z][A-Za-z '\-]{2,30})", summary)
    if not m:
        return
    concept_word = m.group(1).strip().split()[0].lower().rstrip("'")
    script = open(script_path, encoding="utf-8").read().lower()
    if len(concept_word) > 3 and concept_word not in script:
        warnings.append(f"[LEARNING OBJECTIVE MISMATCH] episode_summary.md declares the core concept as "
                        f"'{concept_word}' but that word never appears in complete_script.md — the script "
                        f"may not actually teach the declared lesson (cross-output consistency).")


def check_content_restrictions(episode_dir, root, errors, warnings):
    """Section 34-40: scans all generated text outputs for restricted
    elements from phase2/data/safety/content_restrictions.json. Extends
    this existing checker rather than building a separate engine."""
    restrictions_path = os.path.join(root, "phase2", "data", "safety", "content_restrictions.json")
    if not os.path.exists(restrictions_path):
        return
    restrictions = json.load(open(restrictions_path, encoding="utf-8"))["restrictions"]

    # Only flag NEVER_GENERATE items automatically; REVIEW_REQUIRED items
    # are surfaced as warnings (need human/context judgment, not auto-fail).
    scan_files = [f for f in os.listdir(episode_dir)
                  if os.path.isfile(os.path.join(episode_dir, f)) and f.endswith((".md", ".srt"))]

    for r in restrictions:
        level = r["level"]
        if level not in ("NEVER_GENERATE", "REVIEW_REQUIRED"):
            continue
        pattern = re.compile(r"\b(" + "|".join(re.escape(a) for a in r["aliases"]) + r")\b", re.IGNORECASE)
        for fname in scan_files:
            content = open(os.path.join(episode_dir, fname), encoding="utf-8").read()
            for m in pattern.finditer(content):
                # allow an explicit, cited educational exception: if the
                # same file also cites a real source_id near the match,
                # treat as CONTEXT_ONLY rather than a violation
                window = content[max(0, m.start()-150):m.start()+150]
                has_citation_nearby = bool(re.search(r"\b(?:qv|dua|hd)_\d+\b", window))
                if has_citation_nearby and "CONTEXT_ONLY" in str(r.get("script_mention", "")):
                    continue
                target = errors if level == "NEVER_GENERATE" else warnings
                target.append(f"[CONTENT RESTRICTION: {r['restriction_id']} — {r['canonical_name']}] "
                              f"{fname}: found '{m.group(0)}' ({level}, {r['category']}) with no nearby "
                              f"citation exempting it.")

    # General child-safety rules (v2.36) -- same enforcement path, second
    # data source. Distinct from the Islamic-specific restrictions above:
    # these are sexual-content/language/violence/hate/extremism/animal-
    # cruelty rules that were previously entirely unenforced.
    safety_path = os.path.join(root, "phase2", "data", "safety", "content_scene_safety_registry.json")
    if os.path.exists(safety_path):
        safety_rules = json.load(open(safety_path, encoding="utf-8"))["rules"]
        for r in safety_rules:
            if r["decision"] not in ("BLOCK", "REVIEW_REQUIRED") or not r.get("aliases"):
                continue
            pattern = re.compile(r"\b(" + "|".join(re.escape(a) for a in r["aliases"]) + r")\b", re.IGNORECASE)
            for fname in scan_files:
                content = open(os.path.join(episode_dir, fname), encoding="utf-8").read()
                for m in pattern.finditer(content):
                    target = errors if r["decision"] == "BLOCK" else warnings
                    target.append(f"[SAFETY: {r['rule_id']} — {r['category']}] {fname}: found "
                                  f"'{m.group(0)}' ({r['decision']}). {r['description']}")


    # Indirect sacred-entity depiction heuristic (addresses a real false
    # negative found during testing: "a figure representing Allah" isn't
    # caught by literal alias matching alone). Imperfect by construction —
    # keyword proximity, not semantic understanding — but catches the
    # most common phrasing pattern for an indirect depiction request.
    depiction_words = ("figure", "depicting", "depicts", "represents", "representing",
                       "appearance of", "looks like", "shown as", "visualized as", "image of")
    sacred_names = ("allah", "the prophet muhammad", "prophet nuh", "prophet yunus")
    for fname in scan_files:
        content = open(os.path.join(episode_dir, fname), encoding="utf-8").read()
        content_lower = content.lower()
        for name in sacred_names:
            for m in re.finditer(re.escape(name), content_lower):
                window = content_lower[max(0, m.start()-40):m.start()+40]
                if any(dw in window for dw in depiction_words):
                    errors.append(f"[CONTENT RESTRICTION: indirect sacred-entity depiction] {fname}: "
                                  f"'{name}' appears near a depiction word ({window.strip()}) — possible "
                                  f"indirect visual depiction request, not caught by literal alias matching. "
                                  f"Human review recommended even if this is a false positive.")


def cmd_check_episode(episode_dir, root):
    errors = []
    warnings = []

    # P0-5: character lock byte-match. Load every canonical character's
    # locked block, then confirm image_prompts.md / thumbnail.md contain
    # that exact text wherever the character is mentioned.
    char_dir = os.path.join(root, "sources", "characters", "characters")
    locked_blocks = {}
    if os.path.isdir(char_dir):
        for fname in os.listdir(char_dir):
            if not fname.endswith(".md"):
                continue
            name = fname[:-3]
            text = open(os.path.join(char_dir, fname), encoding="utf-8").read()
            block = extract_locked_block(text)
            if block:
                locked_blocks[name] = block

    scan_files = ["image_prompts.md", "thumbnail.md"]
    for sf in scan_files:
        path = os.path.join(episode_dir, sf)
        if not os.path.exists(path):
            continue
        content = open(path, encoding="utf-8").read()
        norm_content = normalize_whitespace(content)
        for char_name, block in locked_blocks.items():
            norm_block = normalize_whitespace(block)
            first_words = " ".join(block.split()[:4])
            if first_words.split(",")[0].split("—")[0].strip() in content or char_name.capitalize() in content:
                if norm_block not in norm_content:
                    errors.append(f"[CHARACTER LOCK MISMATCH] {sf}: mentions '{char_name}' but the exact "
                                  f"canonical locked description block is not present verbatim (compared with "
                                  f"whitespace/line-wrap normalized) — possible reconstruction/paraphrase "
                                  f"instead of inlining (P0-5).")

    if not locked_blocks:
        warnings.append("No canonical locked character blocks found in repository to check against — "
                         "cannot confirm character-lock integrity (repository may be incomplete; run preflight_check.py).")

    # P1-16/17/18: excluded-claim propagation scan. Reads
    # missing_knowledge_report.md's excluded/rejected claims (if present)
    # and confirms none of that literal text reappears elsewhere as if
    # it were an accepted claim.
    mkr_path = os.path.join(episode_dir, "missing_knowledge_report.md")
    excluded_phrases = []
    if os.path.exists(mkr_path):
        content = open(mkr_path, encoding="utf-8").read()
        # Only treat a quoted phrase as "excluded" if it co-occurs, on the
        # same line/table-row, with actual rejection language — otherwise
        # this false-positives on quotes that merely mention the episode
        # title or an accepted claim (found and fixed during v2.17
        # anti-false-pass testing: "The Day Zayd Chose to Be Honest" was
        # being flagged as excluded purely because it appeared in quotes
        # near the word "produced", not because it was ever rejected).
        rejection_markers = ("no quran verse", "no entry supports", "no direct citation",
                              "unsupported", "not yet available", "0 matches", "no hadith",
                              "no matches", "rejected", "excluded", "no repository evidence",
                              "zero matches", "no support")
        for line in content.split("\n"):
            line_lower = line.lower()
            if not any(marker in line_lower for marker in rejection_markers):
                continue
            excluded_phrases.extend(re.findall(r'"([^"]{15,120})"', line))

    if excluded_phrases:
        all_other_files = [f for f in os.listdir(episode_dir) if f != "missing_knowledge_report.md" and os.path.isfile(os.path.join(episode_dir, f))]
        for fname in all_other_files:
            try:
                content = open(os.path.join(episode_dir, fname), encoding="utf-8").read()
            except Exception:
                continue
            for phrase in excluded_phrases:
                if phrase in content:
                    errors.append(f"[EXCLUDED CLAIM REAPPEARED] '{phrase[:60]}...' was flagged as "
                                  f"unsupported/excluded in missing_knowledge_report.md but appears "
                                  f"verbatim in {fname} (P1-16).")

    print(f"Checked: {episode_dir}")
    print(f"Character locks checked: {len(locked_blocks)}")
    print(f"Excluded-claim phrases tracked: {len(excluded_phrases)}")

    check_source_ids_resolve(episode_dir, root, errors)
    check_review_queue_invariants(root, errors)
    check_semantic_overreach(episode_dir, root, errors, warnings)
    check_paraphrase_as_quotation(episode_dir, root, errors)
    check_unquoted_religious_attribution(episode_dir, root, errors)
    check_character_resolution(episode_dir, root, errors)
    check_learning_objective_consistency(episode_dir, root, errors, warnings)
    check_content_restrictions(episode_dir, root, errors, warnings)

    if warnings:
        print(f"\nWARNINGS ({len(warnings)}):")
        for w in warnings:
            print("  " + w)
    if errors:
        print(f"\nERRORS ({len(errors)}):")
        for e in errors:
            print("  " + e)
        print("\nvalidation: FAIL")
        sys.exit(1)
    else:
        print("\nPASS — no character-lock mismatches, no excluded-claim propagation detected.")
        sys.exit(0)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(2)
    cmd = sys.argv[1]
    if cmd == "snapshot":
        cmd_snapshot(sys.argv[2] if len(sys.argv) > 2 else ".")
    elif cmd == "verify":
        cmd_verify(sys.argv[2] if len(sys.argv) > 2 else ".")
    elif cmd == "check-episode":
        if len(sys.argv) < 3:
            print("Usage: check-episode <output_package_dir> [repo_root]")
            sys.exit(2)
        cmd_check_episode(sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else ".")
    else:
        print(__doc__)
        sys.exit(2)


if __name__ == "__main__":
    main()
